# Name: Tom Abraham
# Student ID: 917096660

all:
	g++ -Wall -o calculator Fraction.cpp calculator.cpp 
	g++ -Wall -o useFraction Fraction.cpp useFraction.cpp

clean:
	rm -f *.o calculator 
	rm -f *.o useFraction 